const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || "https://shapam-ecomerce-backend.onrender.com/api";

// Helper function to get token
const getAuthToken = (): string | null => {
  if (typeof window === 'undefined') return null;
  const localToken = localStorage.getItem("authToken");
  const sessionToken = sessionStorage.getItem("authToken");
  return localToken || sessionToken;
};

export interface DisciplineRecord {
  id: string;
  userId: string;
  role: string;
  type: "STRIKE" | "SUSPENSION" | "APPEAL";
  status: "ACTIVE" | "RESOLVED" | "EXPIRED";
  reason: string;
  isAutoGenerated: boolean;
  suspendedFrom: string | null;
  suspendedUntil: string | null;
  durationDays: number | null;
  appealText: string | null;
  appealStatus: string | null;
  appealResponse: string | null;
  adminNote: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface DisciplineSummary {
  totalStrikes: number;
  activeStrikes: number;
  totalSuspensions: number;
  activeSuspensions: number;
  isSuspended: boolean;
  suspensionEndsAt: string | null;
  lastStrikeDate?: string;
  lastSuspensionDate?: string;
}

export interface ApiResponse<T> {
  message: string;
  data: T;
  statusCode?: number;
}

// Issue a strike - FIXED: Now accepts role parameter
export const issueStrike = async (
  userId: string, 
  reason: string, 
  role: "BUYER" | "SELLER" = "BUYER"
): Promise<ApiResponse<string>> => {
  const token = getAuthToken();
  
  const response = await fetch(`${API_BASE_URL}/discipline/${userId}/strike`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(token && { Authorization: `Bearer ${token}` }),
    },
    body: JSON.stringify({
      role,
      reason,
    }),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || "Failed to issue strike");
  }

  return response.json();
};

// Issue a suspension - FIXED: Now accepts role parameter
export const issueSuspension = async (
  userId: string,
  reason: string,
  durationDays: number = 7,
  role: "BUYER" | "SELLER" = "BUYER"
): Promise<ApiResponse<string>> => {
  const token = getAuthToken();
  
  const response = await fetch(`${API_BASE_URL}/discipline/${userId}/suspension`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(token && { Authorization: `Bearer ${token}` }),
    },
    body: JSON.stringify({
      role,
      durationDays,
      reason,
    }),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || "Failed to issue suspension");
  }

  return response.json();
};

// Suspend Seller - specific function for sellers
export const SuspendSeller = async (
  userId: string,
  reason: string,
  durationDays: number = 7
): Promise<ApiResponse<string>> => {
  return issueSuspension(userId, reason, durationDays, "SELLER");
};

// Get user discipline summary - FIXED: Proper error handling
export const getUserDisciplineSummary = async (userId: string): Promise<DisciplineSummary> => {
  const token = getAuthToken();
  
  try {
    const response = await fetch(`${API_BASE_URL}/discipline/summary?userId=${userId}`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        ...(token && { Authorization: `Bearer ${token}` }),
      },
    });

    if (!response.ok) {
      // Return default values if request fails
      return {
        totalStrikes: 0,
        activeStrikes: 0,
        totalSuspensions: 0,
        activeSuspensions: 0,
        isSuspended: false,
        suspensionEndsAt: null,
      };
    }

    const data = await response.json();
    return data.data || data;
  } catch (error) {
    console.error("Error fetching discipline summary:", error);
    // Return default values on error
    return {
      totalStrikes: 0,
      activeStrikes: 0,
      totalSuspensions: 0,
      activeSuspensions: 0,
      isSuspended: false,
      suspensionEndsAt: null,
    };
  }
};

// Get all discipline records - FIXED: Better error handling
export const getDisciplineRecords = async (role: "BUYER" | "SELLER"): Promise<DisciplineRecord[]> => {
  const token = getAuthToken();
  
  try {
    const response = await fetch(`${API_BASE_URL}/discipline?role=${role}&limit=100&sortBy=createdAt&sortDir=desc`, {
      method: "GET",
      headers: {
        "Content-Type": "application/json",
        ...(token && { Authorization: `Bearer ${token}` }),
      },
    });

    if (!response.ok) {
      console.error("Failed to fetch discipline records");
      return [];
    }

    const result = await response.json();
    return result.data?.items || result.data || [];
  } catch (error) {
    console.error("Error fetching discipline records:", error);
    return [];
  }
};

// Group discipline records by user - FIXED: Better handling
export const getGroupedDisciplineRecords = async (role: "BUYER" | "SELLER"): Promise<DisciplineRecord[]> => {
  try {
    const allRecords = await getDisciplineRecords(role);
    
    if (!Array.isArray(allRecords) || allRecords.length === 0) {
      return [];
    }
    
    // Group by userId
    const userMap = new Map<string, DisciplineRecord[]>();
    
    allRecords.forEach(record => {
      if (!userMap.has(record.userId)) {
        userMap.set(record.userId, []);
      }
      userMap.get(record.userId)!.push(record);
    });
    
    // For each user, get their active suspension OR their most recent strike
    const displayRecords: DisciplineRecord[] = [];
    
    userMap.forEach((records) => {
      // Check if user has active suspension
      const activeSuspension = records.find(r => r.type === "SUSPENSION" && r.status === "ACTIVE");
      
      if (activeSuspension) {
        // Show the suspension
        displayRecords.push(activeSuspension);
      } else {
        // Show the most recent strike with count
        const strikes = records.filter(r => r.type === "STRIKE" && r.status === "ACTIVE");
        if (strikes.length > 0) {
          // Get the most recent strike
          const latestStrike = strikes.reduce((latest, current) => 
            new Date(current.createdAt) > new Date(latest.createdAt) ? current : latest
          );
          displayRecords.push(latestStrike);
        }
      }
    });
    
    // Sort by most recent
    return displayRecords.sort((a, b) => 
      new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
    );
  } catch (error) {
    console.error("Error grouping discipline records:", error);
    return [];
  }
};

// Get strike count for a specific user - FIXED: Better error handling
export const getUserStrikeCount = async (userId: string, role: "BUYER" | "SELLER"): Promise<number> => {
  try {
    const allRecords = await getDisciplineRecords(role);
    if (!Array.isArray(allRecords)) return 0;
    
    const userStrikes = allRecords.filter(
      r => r.userId === userId && r.type === "STRIKE" && r.status === "ACTIVE"
    );
    return userStrikes.length;
  } catch (error) {
    console.error("Error fetching strike count:", error);
    return 0;
  }
};

// Revoke/Clear a discipline action - FIXED: Better error handling
export const revokeDisciplineAction = async (actionId: string): Promise<void> => {
  const token = getAuthToken();
  
  const response = await fetch(`${API_BASE_URL}/discipline/${actionId}`, {
    method: "DELETE",
    headers: {
      "Content-Type": "application/json",
      ...(token && { Authorization: `Bearer ${token}` }),
    },
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || "Failed to revoke action");
  }
};

// Extend suspension - FIXED: Proper implementation
export const extendSuspension = async (
  userId: string,
  additionalDays: number,
  reason: string,
  role: "BUYER" | "SELLER" = "BUYER"
): Promise<ApiResponse<string>> => {
  const token = getAuthToken();
  
  const response = await fetch(`${API_BASE_URL}/discipline/${userId}/suspension`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(token && { Authorization: `Bearer ${token}` }),
    },
    body: JSON.stringify({
      role,
      durationDays: additionalDays,
      reason: `Extension: ${reason}`,
    }),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || "Failed to extend suspension");
  }

  return response.json();
};

// Submit appeal - NEW
export const submitAppeal = async (
  actionId: string,
  appealText: string
): Promise<ApiResponse<string>> => {
  const token = getAuthToken();
  
  const response = await fetch(`${API_BASE_URL}/discipline/${actionId}/appeal`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(token && { Authorization: `Bearer ${token}` }),
    },
    body: JSON.stringify({ appealText }),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || "Failed to submit appeal");
  }

  return response.json();
};

// Approve or reject appeal - NEW
export const appealDecision = async (
  actionId: string,
  decision: "APPROVED" | "REJECTED",
  reason?: string
): Promise<ApiResponse<string>> => {
  const token = getAuthToken();

  const response = await fetch(`${API_BASE_URL}/discipline/${actionId}/appeal/decision`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(token && { Authorization: `Bearer ${token}` }),
    },
    body: JSON.stringify({ decision, reason }),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || "Failed to process appeal");
  }

  return response.json();
};

// Reinstate suspension - NEW
export const reinstateSuspension = async (actionId: string): Promise<ApiResponse<string>> => {
  const token = getAuthToken();

  const response = await fetch(`${API_BASE_URL}/discipline/${actionId}/suspension/reinstate`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(token && { Authorization: `Bearer ${token}` }),
    },
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || "Failed to reinstate suspension");
  }

  return response.json();
};

// Clear strike - NEW
export const clearStrike = async (actionId: string): Promise<ApiResponse<string>> => {
  const token = getAuthToken();

  const response = await fetch(`${API_BASE_URL}/discipline/${actionId}/strike/clear`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      ...(token && { Authorization: `Bearer ${token}` }),
    },
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    throw new Error(errorData.message || "Failed to clear strike");
  }

  return response.json();
};