import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import type { ApiResponse } from "../types/auth";
import { authStorage } from "@/lib/auth/authUtils";

export type DisciplineRole = "BUYER" | "SELLER";
export type DisciplineType = "STRIKE" | "SUSPENSION" | "APPEAL";
export type DisciplineStatus = "ACTIVE" | "RESOLVED" | "EXPIRED";
export type AppealStatus = "APPROVED" | "REJECTED";

export interface DisciplineRecord {
  id: string;
  userId: string;
  role: DisciplineRole;
  type: DisciplineType;
  status: DisciplineStatus;
  reason: string;
  isAutoGenerated: boolean;
  suspendedFrom: string | null;
  suspendedUntil: string | null;
  durationDays: number | null;
  appealText: string | null;
  appealStatus: string | null;
  appealResponse: string | null;
  adminNote: string | null;
  evidence?: string[];
  createdAt: string;
  updatedAt: string;
  // populated fields — only present if backend populates them
  user?: {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    phone?: string;
    imageUrl?: string;
  };
}

export interface PaginatedDiscipline {
  items: DisciplineRecord[];
  nextCursor: string | null;
  prevCursor: string | null;
  hasNext: boolean;
  hasPrev: boolean;
  pageSize: number;
}

export interface ListDisciplineParams {
  populate?: string[];
  q?: string;
  limit?: number;
  after?: string;
  before?: string;
  sortBy?: "createdAt" | "name";
  sortDir?: "asc" | "desc";
  role?: DisciplineRole;
  type?: DisciplineType;
  status?: DisciplineStatus;
  userId?: string;
}

export interface IssueStrikeRequest { role: DisciplineRole; reason: string; }
export interface IssueSuspensionRequest { role: DisciplineRole; durationDays: number; reason: string; }
export interface ReinstateRequest { reason: string; }
export interface ClearStrikeRequest { reason: string; }
export interface ExtendSuspensionRequest { additionalDays: number; reason: string; }
export interface SubmitAppealRequest { appealText: string; evidence?: string[]; }
export interface AppealDecisionRequest { appealStatus: AppealStatus; adminNote: string; }

const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL ||
  "https://shapam-ecomerce-backend.onrender.com/api";

// ─── Helper: fetch a single user by ID (used when populate doesn't return user) ─
export const fetchUserById = async (userId: string): Promise<{ firstName: string; lastName: string; email: string }> => {
  const token = authStorage.getAccessToken();
  try {
    const res = await fetch(`${API_BASE_URL}/user/${userId}`, {
      headers: {
        "Content-Type": "application/json",
        ...(token && { Authorization: `Bearer ${token}` }),
      },
    });
    if (!res.ok) throw new Error("Failed");
    const data = await res.json();
    const u = data.data;
    return {
      firstName: u?.firstName || "Unknown",
      lastName: u?.lastName || "User",
      email: u?.email || "N/A",
    };
  } catch {
    return { firstName: "Unknown", lastName: "User", email: "N/A" };
  }
};

/**
 * Helper to fetch a user's discipline summary from the raw /discipline endpoint.
 * This aggregates active strikes and suspensions.
 */
export const getUserDisciplineSummary = async (userId: string) => {
  const token = authStorage.getAccessToken();
  try {
    const res = await fetch(`${API_BASE_URL}/discipline?userId=${userId}&limit=50`, {
      headers: {
        "Content-Type": "application/json",
        ...(token && { Authorization: `Bearer ${token}` }),
      },
    });

    if (!res.ok) throw new Error("Failed to fetch discipline records");
    
    const data = await res.json();
    const records: DisciplineRecord[] = data.data.items || [];

    const activeStrikes = records.filter(
      (r) => r.type === "STRIKE" && r.status === "ACTIVE"
    ).length;

    // A suspension is considered active if:
    // 1. Its status is "ACTIVE"
    // 2. OR it is under appeal but the appeal hasn't been APPROVED yet
    const activeSuspensionsRecords = records.filter(
      (r) => r.type === "SUSPENSION" && (r.status === "ACTIVE" || (r.appealStatus !== "APPROVED" && r.appealText))
    );

    return {
      activeStrikes,
      isSuspended: activeSuspensionsRecords.length > 0,
      activeSuspensions: activeSuspensionsRecords.length,
      records
    };
  } catch (err) {
    console.error("Error in getUserDisciplineSummary:", err);
    return {
      activeStrikes: 0,
      isSuspended: false,
      activeSuspensions: 0,
      records: []
    };
  }
};

const baseQuery = fetchBaseQuery({
  baseUrl: API_BASE_URL,
  prepareHeaders: (headers) => {
    const token = authStorage.getAccessToken();
    if (token) headers.set("authorization", `Bearer ${token}`);
    headers.set("content-type", "application/json");
    return headers;
  },
});

const baseQueryWithReauth = async (
  args: Parameters<typeof baseQuery>[0],
  api: Parameters<typeof baseQuery>[1],
  extraOptions: Parameters<typeof baseQuery>[2]
) => {
  let result = await baseQuery(args, api, extraOptions);
  if (result?.error?.status === 401) {
    const refreshToken = authStorage.getRefreshToken();
    if (refreshToken) {
      try {
        const refreshResult = await baseQuery(
          { url: "/auth/refresh", method: "POST", body: { refreshToken } },
          api,
          extraOptions
        );
        if (refreshResult?.data && typeof refreshResult.data === "object") {
          const refreshData = refreshResult.data as { accessToken: string; refreshToken?: string };
          authStorage.setTokens(refreshData.accessToken, refreshData.refreshToken);
          result = await baseQuery(args, api, extraOptions);
          return result;
        }
      } catch (error) {
        console.error("Token refresh failed:", error);
      }
    }
    if (result?.error?.status === 401) authStorage.clearTokens();
  }
  return result;
};

export const disciplineApi = createApi({
  reducerPath: "disciplineApi",
  baseQuery: baseQueryWithReauth,
  tagTypes: ["Discipline"],
  endpoints: (builder) => ({
    getDisciplineRecords: builder.query<ApiResponse<PaginatedDiscipline>, ListDisciplineParams>({
      query: (params = {}) => ({ url: "/discipline", method: "GET", params }),
      providesTags: (result) =>
        result
          ? [...result.data.items.map(({ id }) => ({ type: "Discipline" as const, id })), { type: "Discipline" as const, id: "LIST" }]
          : [{ type: "Discipline" as const, id: "LIST" }],
    }),
    getDisciplineSummary: builder.query<ApiResponse<Record<string, unknown>>, void>({
      query: () => ({ url: "/discipline/summary", method: "GET" }),
      providesTags: ["Discipline"],
    }),
    issueStrike: builder.mutation<ApiResponse<string>, { userId: string; data: IssueStrikeRequest }>({
      query: ({ userId, data }) => ({ url: `/discipline/${userId}/strike`, method: "POST", body: data }),
      invalidatesTags: [{ type: "Discipline", id: "LIST" }],
    }),
    issueSuspension: builder.mutation<ApiResponse<string>, { userId: string; data: IssueSuspensionRequest }>({
      query: ({ userId, data }) => ({ url: `/discipline/${userId}/suspension`, method: "POST", body: data }),
      invalidatesTags: [{ type: "Discipline", id: "LIST" }],
    }),
    reinstateSuspension: builder.mutation<ApiResponse<string>, { actionId: string; data: ReinstateRequest }>({
      query: ({ actionId, data }) => ({ url: `/discipline/${actionId}/suspension/reinstate`, method: "POST", body: data }),
      invalidatesTags: [{ type: "Discipline", id: "LIST" }],
    }),
    clearStrike: builder.mutation<ApiResponse<string>, { actionId: string; data: ClearStrikeRequest }>({
      query: ({ actionId, data }) => ({ url: `/discipline/${actionId}/strike/clear`, method: "POST", body: data }),
      invalidatesTags: (result, error, { actionId }) => [{ type: "Discipline", id: actionId }, { type: "Discipline", id: "LIST" }],
    }),
    extendSuspension: builder.mutation<ApiResponse<string>, { actionId: string; data: ExtendSuspensionRequest }>({
      query: ({ actionId, data }) => ({ url: `/discipline/${actionId}/suspension/extend`, method: "PATCH", body: data }),
      invalidatesTags: (result, error, { actionId }) => [{ type: "Discipline", id: actionId }, { type: "Discipline", id: "LIST" }],
    }),
    submitAppeal: builder.mutation<ApiResponse<string>, { actionId: string; data: SubmitAppealRequest }>({
      query: ({ actionId, data }) => ({ url: `/discipline/${actionId}/appeal`, method: "POST", body: data }),
      invalidatesTags: [{ type: "Discipline", id: "LIST" }],
    }),
    appealDecision: builder.mutation<ApiResponse<string>, { actionId: string; data: AppealDecisionRequest }>({
      query: ({ actionId, data }) => ({ url: `/discipline/${actionId}/appeal/decision`, method: "POST", body: data }),
      invalidatesTags: (result, error, { actionId }) => [{ type: "Discipline", id: actionId }, { type: "Discipline", id: "LIST" }],
    }),
  }),
});

export const {
  useGetDisciplineRecordsQuery,
  useLazyGetDisciplineRecordsQuery,
  useGetDisciplineSummaryQuery,
  useIssueStrikeMutation,
  useIssueSuspensionMutation,
  useReinstateSuspensionMutation,
  useClearStrikeMutation,
  useExtendSuspensionMutation,
  useSubmitAppealMutation,
  useAppealDecisionMutation,
} = disciplineApi;